import { FlakinessReport } from '../core/types';

export class GithubReporter {
  report(result: FlakinessReport): string {
    const lines: string[] = [];

    lines.push('## Flaky Test Detective Report');
    lines.push('');

    const rateEmoji = result.overallFlakinessRate > 0.2 ? ':red_circle:' : result.overallFlakinessRate > 0.05 ? ':yellow_circle:' : ':green_circle:';

    lines.push(`| Metric | Value |`);
    lines.push(`|--------|-------|`);
    lines.push(`| Tests Tracked | ${result.totalTests} |`);
    lines.push(`| Flaky Tests | ${result.flakyTests} |`);
    lines.push(`| Quarantined | ${result.quarantinedTests} |`);
    lines.push(`| Flakiness Rate | ${rateEmoji} ${(result.overallFlakinessRate * 100).toFixed(1)}% |`);
    lines.push('');

    if (result.records.length === 0) {
      lines.push('No flaky tests detected.');
      return lines.join('\n');
    }

    lines.push('### Flaky Tests');
    lines.push('');
    lines.push('| Test | Score | Runs | Pass/Fail | Patterns | Status |');
    lines.push('|------|-------|------|-----------|----------|--------|');

    for (const record of result.records.slice(0, 20)) {
      const patterns = record.patterns.map((p) => `\`${p.type}\``).join(' ') || '-';
      const status = record.quarantined ? ':no_entry: Quarantined' : ':white_check_mark: Active';
      lines.push(
        `| ${record.name} | ${(record.flakinessScore * 100).toFixed(0)}% | ${record.totalRuns} | ${record.passCount}/${record.failCount} | ${patterns} | ${status} |`
      );
    }

    if (result.records.length > 20) {
      lines.push(`| ... | ${result.records.length - 20} more flaky tests | | | | |`);
    }

    lines.push('');

    const quarantined = result.records.filter((r) => r.quarantined);
    if (quarantined.length > 0) {
      lines.push('<details>');
      lines.push('<summary>Quarantine grep pattern</summary>');
      lines.push('');
      lines.push('```bash');
      const pattern = quarantined.map((r) => r.name.replace(/[.*+?^${}()|[\]\\]/g, '\\$&')).join('|');
      lines.push(`npx playwright test --grep-invert "${pattern}"`);
      lines.push('```');
      lines.push('</details>');
    }

    lines.push('');
    lines.push('---');
    lines.push('*Generated by [flaky-test-detective](https://github.com/mustafaautomation/flaky-test-detective)*');

    return lines.join('\n');
  }
}
